name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v5

     # Install Rust
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Install llvm tools
    - name: Install llvm-tools component explicitly
      run: rustup component add llvm-tools-preview --toolchain stable

    # Install just
    - name: Install just
      run: cargo install just

    # Install dependencies for pcap
    - name: Install libpcap
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev pkg-config

    # Install llvm dependencies
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    # Install llvm
    - name: Install llvm
      run: cargo install cargo-llvm-cov

    # Build
    - name: Build
      run: just build

    # Tests
    - name: Run unit tests
      run: just unit

    # Run coverage check, keeping 0 for now
    - name: Run coverage check
      run: just cov-check 0
